// <auto-generated />
using System;
using Miao.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Miao.Core.Migrations
{
    [DbContext(typeof(MiaoDbContext))]
    [Migration("20260820021734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Miao.Core.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VolumeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Miao.Core.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterGroupId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Miao.Core.Models.CharacterAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAliases");
                });

            modelBuilder.Entity("Miao.Core.Models.CharacterGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerNovelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerNovelId");

                    b.ToTable("CharacterGroups");
                });

            modelBuilder.Entity("Miao.Core.Models.CustomLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomLibraries");
                });

            modelBuilder.Entity("Miao.Core.Models.CustomLibraryNovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomLibraryId");

                    b.HasIndex("NovelId");

                    b.ToTable("CustomLibraryNovels");
                });

            modelBuilder.Entity("Miao.Core.Models.GlossarySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerNovelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerNovelId");

                    b.ToTable("GlossarySets");
                });

            modelBuilder.Entity("Miao.Core.Models.GlossarySetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlossarySetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HanViet")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinYin")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlossarySetId");

                    b.ToTable("GlossarySetEntries");
                });

            modelBuilder.Entity("Miao.Core.Models.NoteEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Miao.Core.Models.Novel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastReadChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelCharacterGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterGroupId");

                    b.HasIndex("NovelId", "CharacterGroupId")
                        .IsUnique();

                    b.ToTable("NovelCharacterGroups");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelGlossarySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GlossarySetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlossarySetId");

                    b.HasIndex("NovelId", "GlossarySetId")
                        .IsUnique();

                    b.ToTable("NovelGlossarySets");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("NovelLinks");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.ToTable("NovelSources");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NovelId");

                    b.HasIndex("TagId");

                    b.ToTable("NovelTags");
                });

            modelBuilder.Entity("Miao.Core.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Miao.Core.Models.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NovelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("Miao.Core.Models.Chapter", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany("Chapters")
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.Character", b =>
                {
                    b.HasOne("Miao.Core.Models.CharacterGroup", "CharacterGroup")
                        .WithMany("Characters")
                        .HasForeignKey("CharacterGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterGroup");
                });

            modelBuilder.Entity("Miao.Core.Models.CharacterAlias", b =>
                {
                    b.HasOne("Miao.Core.Models.Character", "Character")
                        .WithMany("Aliases")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Miao.Core.Models.CharacterGroup", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "OwnerNovel")
                        .WithMany()
                        .HasForeignKey("OwnerNovelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerNovel");
                });

            modelBuilder.Entity("Miao.Core.Models.CustomLibraryNovel", b =>
                {
                    b.HasOne("Miao.Core.Models.CustomLibrary", "CustomLibrary")
                        .WithMany("Items")
                        .HasForeignKey("CustomLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomLibrary");

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.GlossarySet", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "OwnerNovel")
                        .WithMany()
                        .HasForeignKey("OwnerNovelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerNovel");
                });

            modelBuilder.Entity("Miao.Core.Models.GlossarySetEntry", b =>
                {
                    b.HasOne("Miao.Core.Models.GlossarySet", "GlossarySet")
                        .WithMany("Entries")
                        .HasForeignKey("GlossarySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlossarySet");
                });

            modelBuilder.Entity("Miao.Core.Models.NoteEntry", b =>
                {
                    b.HasOne("Miao.Core.Models.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelCharacterGroup", b =>
                {
                    b.HasOne("Miao.Core.Models.CharacterGroup", "CharacterGroup")
                        .WithMany()
                        .HasForeignKey("CharacterGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterGroup");

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelGlossarySet", b =>
                {
                    b.HasOne("Miao.Core.Models.GlossarySet", "GlossarySet")
                        .WithMany()
                        .HasForeignKey("GlossarySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlossarySet");

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelLink", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelSource", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("Miao.Core.Models.NovelTag", b =>
                {
                    b.HasOne("Miao.Core.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miao.Core.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novel");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Miao.Core.Models.Chapter", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Miao.Core.Models.Character", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("Miao.Core.Models.CharacterGroup", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Miao.Core.Models.CustomLibrary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Miao.Core.Models.GlossarySet", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Miao.Core.Models.Novel", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
